name: Build 2025 BOM Workflow (LuaLaTeX)

on:
  push:
    paths:
      - 'papers/2025_bom_workflow/**'
      - '.github/workflows/latex_bom_workflow.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- TeX Live & フォント ----
      - name: Install TeX Live & HaranoAji Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full fonts-haranoaji

      # ---- LuaLaTeX コンパイル ----
      - name: Compile with LuaLaTeX
        working-directory: papers/2025_bom_workflow
        run: |
          lualatex -interaction=nonstopmode -file-line-error main.tex | tee build.log
          lualatex -interaction=nonstopmode -file-line-error main.tex | tee -a build.log
          lualatex -interaction=nonstopmode -file-line-error main.tex | tee -a build.log

      # ---- 成果物アップロード（失敗時もログ保存）----
      - name: Upload PDF and logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 2025_bom_workflow_build
          path: |
            papers/2025_bom_workflow/main.pdf
            papers/2025_bom_workflow/*.log
            papers/2025_bom_workflow/build.log
          retention-days: 14
